name: Prettier code formatter

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v5
      - name: Install Prettier 💾
        run: npm ci
      - name: Prettier Check 🔎
        run: npx prettier . --check
